// Image pipeline (sharp). Run: `npm run images`
// ILD's Texas fal set (sources copied from clients/internet-loans-direct/funnels/lenderdscr/public/images):
//   assets-src/aerial-golden.png  -> public/images/ild-aerial-golden.webp (1600 wide max, q70): StatsBand texture
//   assets-src/hero-property.png  -> public/images/ild-hero-property.webp (1024 wide, q70): HowItWorks accent photo
//   public/images/og.jpg (1200x630): aerial cover-cropped + solid ink band, bottom third, NO text
//   src/data/lqip.ts: 24px-wide base64 data URI per image (background placeholders)
// Do not generate new imagery for the LP (BRIEF section 8).
// /texas-airbnb-vrbo-dscr-loans (fal flux-pro set, 2026-10-03), each at 720 (a 412px
// phone at dsf 1.75 needs 651) + a desktop width:
//   assets-src/str-hill-country.png  -> texas-hill-country-short-term-rental[-720].webp (hero)
//   assets-src/str-gulf-coast.png    -> texas-gulf-coast-beach-house-rental[-720].webp (rural card)
//   assets-src/str-austin-duplex.png -> austin-duplex-short-term-rental[-720].webp (who-it-is-for)
//   public/images/og-texas-airbnb-vrbo-dscr-loans.jpg (1200x630): hill country cover-cropped, NO text
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = (f) => path.join(root, 'assets-src', f);
const out = (f) => path.join(root, 'public', 'images', f);

const INK = '#1a1418';

const jobs = [
  { key: 'aerialGolden', from: 'aerial-golden.png', to: 'ild-aerial-golden.webp', width: 1600 },
  // rendered at <= 480 CSS px (HowItWorks figure), so 880 covers dsf2 with margin
  { key: 'heroProperty', from: 'hero-property.png', to: 'ild-hero-property.webp', width: 880 },
  // hero figure renders <= 544 CSS px on desktop, viewport minus gutters on phones
  { key: 'strHillCountry', from: 'str-hill-country.png', to: 'texas-hill-country-short-term-rental.webp', width: 1120 },
  { key: 'strHillCountrySm', from: 'str-hill-country.png', to: 'texas-hill-country-short-term-rental-720.webp', width: 720, lqip: false },
  { key: 'strGulfCoast', from: 'str-gulf-coast.png', to: 'texas-gulf-coast-beach-house-rental.webp', width: 960 },
  { key: 'strGulfCoastSm', from: 'str-gulf-coast.png', to: 'texas-gulf-coast-beach-house-rental-720.webp', width: 720, lqip: false },
  { key: 'strAustinDuplex', from: 'str-austin-duplex.png', to: 'austin-duplex-short-term-rental.webp', width: 960 },
  { key: 'strAustinDuplexSm', from: 'str-austin-duplex.png', to: 'austin-duplex-short-term-rental-720.webp', width: 720, lqip: false },
];

async function lqip(file) {
  const buf = await sharp(file).resize({ width: 24 }).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buf.toString('base64')}`;
}

async function main() {
  await mkdir(out(''), { recursive: true });
  const lqips = {};
  const dims = {};

  for (const j of jobs) {
    const info = await sharp(src(j.from))
      .resize({ width: j.width, withoutEnlargement: true })
      .webp({ quality: 70, effort: 5 })
      .toFile(out(j.to));
    if (j.lqip !== false) lqips[j.key] = await lqip(src(j.from));
    dims[j.key] = { width: info.width, height: info.height };
    console.log(`${j.to}: ${info.width}x${info.height}, ${(info.size / 1024).toFixed(0)} KB`);
  }

  // OG image: aerial cover-cropped to 1200x630 with a solid ink band across the
  // bottom third. No text baked in (the title comes from the og:title tag).
  const band = await sharp({
    create: { width: 1200, height: 210, channels: 3, background: INK },
  })
    .png()
    .toBuffer();
  const og = await sharp(src('aerial-golden.png'))
    .resize(1200, 630, { fit: 'cover', position: 'attention' })
    .composite([{ input: band, top: 420, left: 0 }])
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(out('og.jpg'));
  console.log(`og.jpg: ${og.width}x${og.height}, ${(og.size / 1024).toFixed(0)} KB`);

  // The short-term rental page's own OG image: the hill country hero, cover-cropped, no text.
  const ogStr = await sharp(src('str-hill-country.png'))
    .resize(1200, 630, { fit: 'cover', position: 'attention' })
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(out('og-texas-airbnb-vrbo-dscr-loans.jpg'));
  console.log(`og-texas-airbnb-vrbo-dscr-loans.jpg: ${ogStr.width}x${ogStr.height}, ${(ogStr.size / 1024).toFixed(0)} KB`);

  const ts = `// GENERATED by scripts/convert-images.mjs. Do not edit by hand.
// 24px-wide base64 placeholders for background-image LQIPs, plus the rendered
// dimensions of each webp (for width/height attributes).
export const lqip = {
${jobs.filter((j) => j.lqip !== false).map((j) => `  ${j.key}: '${lqips[j.key]}',`).join('\n')}
} as const;

export const imageDims = {
${jobs.map((j) => `  ${j.key}: { width: ${dims[j.key].width}, height: ${dims[j.key].height} },`).join('\n')}
} as const;
`;
  await writeFile(path.join(root, 'src', 'data', 'lqip.ts'), ts, 'utf8');
  console.log('src/data/lqip.ts written');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
