// GENERATED by scripts/convert-images.mjs. Do not edit by hand.
// 24px-wide base64 placeholders for background-image LQIPs.
export const lqip = {
  aerialDusk: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdIMgCvBqb2nnVyMoR5kAA/VLInUpK0V0z9AwLrg0OBX9c0RGY4l2r2zMRqLJQrPCcstY22jlh20J+R5xwgyIHr/mAIT/xYlxqGK3df3oN1z/T1EB5LgB13/XwAAA=',
  duplexDusk: 'data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADwBACdASoYABIAPu1oqk8ppiOiMBgIATAdiWwAnTMJwaoIVuk38SgRYzR6tN8jdgAA/uPzlx8gAsxUwFcRweH0oqqBta4s0Lw0Pn7iqOCXUSmnmbgP2yOnlX80/yWk+YKWTetvB3iSdhLxiVoKYelxOlgk2dSUAZebzzz9gHhcRtCxuYn4sbMUFftUHFoI6HK6ZpzU27bQag45elv2Sm/ULD71Y/0MOXNi+/ghFSgAAA==',
} as const;
