// GENERATED by scripts/convert-images.mjs. Do not edit by hand.
// 24px-wide base64 placeholders for background-image LQIPs, plus the rendered
// dimensions of each webp (for width/height attributes).
export const lqip = {
  aerialGolden: 'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdEf/gPHHzdXeSOUClAAD+eJQUz3bEusDlCINW6pSN+wmVeY9D5Y/wphyTvfyCkoTunIpMYPce3da8DP7YjoKDVrlGJavkWBovi/b0hMs0QXgO9ul/HGHGzmUT2s8h64Dhm/peCJkiDQfBJSSJWTeKIAAA',
  heroProperty: 'data:image/webp;base64,UklGRi4BAABXRUJQVlA4ICIBAAAwBgCdASoYAB4APu1kqE2ppaOiMAgBMB2JbACdMoCpAawLhjVaAmV2UWbjmlFwgru4saJW+dIKmKLAAP7QbknV14aujcdjicM+DWzKNVDxKabnACjZMl0qjejqmyImBYNHJN059Nh+dDgW9T0M8E7vwEVD6RsFzC2jfSBDt9oRRfuNFt/jjBQgAAx1CHzQbJmMfMIZQ3FN/SbxHpQ+03jbmxAPo0ih+zAQCS90rR2S4Ss61uVGm63A3hGgTlc9RCVPwJuQOYKE8BcgQxz+j9FtjHJvYBIvuFAmf/QbN1fMrTkaDJCWQ9Y6JJwP/OlX6nv2DktaSq3r0V5dbmPnQQ/17AHVHMClE4YRXj3htuB9q12UN/cJ4b7wnnCOIazTdDAAAA==',
} as const;

export const imageDims = {
  aerialGolden: { width: 1440, height: 864 },
  heroProperty: { width: 880, height: 1100 },
} as const;
